version: "3"

services:
  app:
    container_name: gsg-app
    build:
      context: ./images
      dockerfile: Dockerfile.app
    ports: 
      - "3000:3000"
    volumes:
      - type: bind
        source: ./container/gsg_app
        target: /usr/app
    working_dir: /usr/app
    command: ["npm", "run", "dev"]

  db:
    container_name: gsg-db
    build:
      context: ./images
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    networks:
      - db_connection
    volumes:
      - ./container/gsg_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  api:
    container_name: gsg-api
    build:
      context: ./images
      dockerfile: Dockerfile.api
    ports:
      - "4000:4000"
    networks:
      - db_connection
    volumes:
      - type: bind
        source: ./container/gsg_api
        target: /usr/api
    working_dir: /usr/api
    command: ["npm", "run", "dev"]

  pgadmin:
    image: dpage/pgadmin4:6.11
    container_name: pgadmin
    ports:
      - 80:80
    networks:
      - db_connection
    volumes:
      - ./container/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db

networks:
  db_connection:
    driver: bridge